# Сокращение размерности

### EM алгоритм

Напомним, как выглядит $EM$ алгоритм. 

$$
\log p(x|\theta) = \int q(z)\log p(x|\theta)dz = \int q(z)\log\dfrac{p(x,z|\theta)}{p(z|x,\theta)}dz = \int q(z)\log\dfrac{p(x,z|\theta)}{q(z)}dz+\int q(z)\log\dfrac{q(z)}{p(z|x,\theta)}dz = \mathcal{L}(q,\theta)+KL(q(z)|p(z|x,\theta))
$$

** E-step ** 
$$ q(z)^{(n+1)} = p(z|x,\theta^{(n)}) $$
** M-step ** 
$$ \theta^{(n+1)} = \max\limits_{\theta} \mathcal{L}(q^{(n+1)},\theta) $$

### PCA как модель с латентными пременными

Процесс генерации данных в модели PCA выглядит следующим образом:

![Генеративный процесс](pca_illustration.png "Генеративный процесс")

Таким образом, мы получаем модель:

\begin{equation}P(X,T|W,\mu,\sigma^2) = \prod\limits_{n=1}^{N}p(x_n,t_n|W,\mu,\sigma^2) = \prod\limits_{n=1}^{N}\mathcal{N}(x_n|Wt_n+\mu,\sigma^2I)\mathcal{N}(t_n|0,I)
\end{equation}

** Задание 1. ** (5 баллов) Выпишите E и M шаги для модели PCA.

$\mathcal{L}_C$ - complete-data log-likelihood function         
$\langle \cdot \rangle$ - expectation           
d - data space dimension             
S - sample covariance matrix             
T - error accounted data matrix            
$1_N$ - vector with N ones             

![](2.png)

For the complete data T and X, the above joint probability distribution can be written as

![](3.png)

and the complete-data log-likelihood function $\mathcal{L}_C$ is

![](4.png)

In order for the EM-PCA to estimate $x_j$ in the E-step, the posterior distribution of $x_j$ given $t_j$ is calculated using Bayes’ rule.

![](5.png)

with

![](6.png)

which is a Gaussian distribution such that

![](7.png)

Note that a matrix identity $W^T (W W^T + \sigma^2 I)^{−1} = (W^T W + \sigma^2 I)^{−1} W^T$ is utilized in the above derivation to save computational costs for matrix inversion (*).  For the M-step, the expectation of $\mathcal{L}_C$ is found as follows.

![](8.png)

where

![](9.png)

![](10.png)

By requiring the derivative of $\langle \mathcal{L}_C \rangle$ with respect to each parameter to vanish, the parameter estimators turn out as

![](11.png)

![](12.png)

Finally, the EM-PCA algorithm reduces to the following form by limiting $\sigma^2$ to infinitesimal for a zero noise case.

![](13.png)

Proof for (*) in 14.png - 16.png

** Задание 2. ** (5 баллов) Реализуйте EM алгоритм для модели PCA

In [5]:
import numpy as np
from numpy.linalg import inv
from numpy import transpose as tr


class PCA(object):
    def __init__(self, q=2, sigma=1.0):
        self.q = q
        self.prior_sigma = sigma

    def fit(self, y):
        self.y = y
        self.p = y.shape[0]
        self.n = y.shape[1]
        [self.w, self.mu, self.sigma] = self.__fit_em()

    def __ell(self, w, mu, sigma, norm=True):
        m = inv(tr(w).dot(w) + sigma * np.eye(w.shape[1]))
        mw = m.dot(tr(w))
        ll = 0.0
        for i in range(self.n):
            yi = self.y[:, i][:, np.newaxis]
            yyi = yi - mu
            xi = mw.dot(yyi)
            xxi = sigma * m + xi.dot(tr(xi))
            ll += 0.5 * np.trace(xxi)
            if sigma > 1e-5:
                ll += (2 * sigma)**(-1) * float(tr(yyi).dot(yyi))
                ll -= sigma**(-1) * float(tr(xi).dot(tr(w)).dot(yyi))
                ll += (2 * sigma)**(-1) * np.trace(tr(w).dot(w).dot(xxi))
        if sigma > 1e-5:
            ll += 0.5 * self.n * self.p * np.log(sigma)
        ll *= -1.0
        if norm:
            ll /= float(self.n)
        return ll

    def __fit_em(self, max_it=100):
        w = np.random.rand(self.p, self.q)
        mu = np.mean(self.y, 1)[:, np.newaxis]
        sigma = self.prior_sigma
        ll = self.__ell(w, mu, sigma)

        yy = self.y - mu
        s = self.n**(-1) * yy.dot(tr(yy))
        for i in range(max_it):
            m = inv(tr(w).dot(w) + sigma * np.eye(self.q))
            t = inv(sigma * np.eye(self.q) + m.dot(tr(w)).dot(s).dot(w))
            w_new = s.dot(w).dot(t)
            sigma_new = self.p**(-1) * np.trace(s - s.dot(w).dot(m).dot(tr(w_new)))
            ll_new = self.__ell(w_new, mu, sigma_new)
            w = w_new
            sigma = sigma_new
            ll = ll_new
        return (w, mu, sigma)

In [6]:
model = PCA()

In [7]:
y = np.random.rand(10, 5)

In [12]:
y

array([[ 0.64786705,  0.9244519 ,  0.15194038,  0.31842225,  0.88663749],
       [ 0.35710602,  0.08625129,  0.22778666,  0.29820592,  0.43705772],
       [ 0.25158284,  0.03052652,  0.94938675,  0.14545179,  0.92980012],
       [ 0.47828738,  0.65129402,  0.70422171,  0.14786224,  0.2218021 ],
       [ 0.30494854,  0.14177862,  0.02826922,  0.29980284,  0.61033674],
       [ 0.53636041,  0.59538634,  0.93660967,  0.04702375,  0.42295589],
       [ 0.49236315,  0.3253516 ,  0.08010441,  0.80670182,  0.75630276],
       [ 0.8982511 ,  0.30693702,  0.06304511,  0.07601901,  0.39971064],
       [ 0.52445366,  0.79688895,  0.49692206,  0.49483858,  0.74506941],
       [ 0.31650554,  0.94042846,  0.04795046,  0.73016825,  0.42204081]])

In [8]:
model.fit(y)

In [9]:
model.w

array([[ 0.08893495, -0.13410495],
       [ 0.08627561,  0.05583572],
       [ 0.01329896,  0.35736019],
       [-0.19862696,  0.01506801],
       [ 0.17041287,  0.01434414],
       [-0.21285162,  0.13133486],
       [ 0.24365406, -0.06374657],
       [ 0.0524461 , -0.04515896],
       [ 0.013977  , -0.04432729],
       [ 0.05775522, -0.27029147]])

In [10]:
model.mu

array([[ 0.58586382],
       [ 0.28128152],
       [ 0.4613496 ],
       [ 0.44069349],
       [ 0.27702719],
       [ 0.50766721],
       [ 0.49216475],
       [ 0.34879258],
       [ 0.61163453],
       [ 0.49141871]])

In [11]:
model.sigma

0.027463765907009614

** Задание 3. ** (10 баллов) Используя свою реализацию метода PCA, решите задачу восстанавления давления по профилю крыла.

Скачать данные со страницы курса. https://yadi.sk/i/065iNGXp3QYv5n

Данные представляют собой матрицу размера $397\times114$; в каждой
строке находится подвектор, описывающий профиль (первые 57
координат), и подвектор, описывающий соответствующее распределение
давления (следующие 57 координат). Задача состоит в том, чтобы на
основании метода главных компонент построить алгоритм, позволяющий
восстанавливать распределение давления по профилю. Опишем алгоритм
обучения и алгоритм восстановления. Пусть ${\bf A}\in\mathbb{R}^{57}$ --
вектор, описывающий профиль, а ${\bf P}\in\mathbb{R}^{57}$ -- вектор,
описывающий распределение давления. Дана обучающая выборка $({\bf
A}_i,{\bf P}_i)_{i=1}^N$ (взять в качестве обучающей выборки 75%
случайно выбранных строк из матрицы данных; остальные 25%
использовать в качестве тестового множества данных).

Алгоритм обучения состоит из следующих шагов:


1. По данным $({\bf A}_i,{\bf P}_i)_{i=1}^N$ оцениваются первые
$d$ (параметр алгоритма) главных компонент ${\bf e}_1,\ldots,{\bf
e}_d$, где ${\bf e}_i\in\mathbb{R}^{114}$. 
2. Каждый из векторов ${\bf e}_i,i=1,\ldots,d$ представляется как объединение двух подвекторов
${\bf e}_i = ({\bf e}_i^A\in\mathbb{R}^{57},{\bf
e}_i^P\in\mathbb{R}^{57}),i=1,\ldots,d$, соответствующих описанию профиля
и распределению давления соответственно.


Преобразование произвольного объединенного вектора ${\bf Z} =
({\bf A},{\bf P})$ в сжатое описание ${\bf\lambda}=(\lambda_1,\ldots,\lambda_d)$ происходит согласно
следующей формуле:

$$
\lambda_i = \left( {\bf Z}-{\bf Z}_{\mathrm{mean}},{\bf e}_i\right),
i=1,\ldots,d,
$$

где ${\bf Z}_{\mathrm{mean}} = \frac{1}{N}\sum_{k=1}^N {\bf Z}_k$,
${\bf Z}_k = ({\bf A}_k,{\bf P}_k)$ (выборочное среднее;
подсчитывается по обучающей выборке). Восстановления подвекторов
${\bf A}$ и ${\bf P}$ объединенного вектора ${\bf Z} = ({\bf
A},{\bf P})$ по сжатому описанию ${\bf
\lambda}=(\lambda_1,\ldots,\lambda_d)$ происходит согласно
формулам

$$
{\bf A}^*({\bf \lambda}) = {\bf A}_{\mathrm{mean}} + \sum_{i=1}^d\lambda_i{\bf e}_i^A,\,{\bf
P}^*({\bf \lambda}) ={\bf P}_{\mathrm{mean}} + \sum_{i=1}^d\lambda_i{\bf e}_i^P.
$$


Алгоритм восстановления давления ${\bf P}$ по профилю ${\bf A}$
может быть описан следующим образом:


1. Для заданного профиля ${\bf A}$ определяются такие ${\bf
\lambda}=(\lambda_1,\ldots,\lambda_d)$, что $\|{\bf A}^*({\bf
\lambda})-{\bf A}\|_{2}^2$ принимает минимальное значение (такое
значение ${\bf \lambda}$ подсчитывается с помощью псевдообращения
матрицы $E=[{\bf e}_1^A,\ldots,{\bf e}_d^A]$, то есть ${\bf
\lambda} = E^{+}\left({\bf A}-{\bf A}_{\mathrm{mean}}\right)$, где $E^+$ -- псевдообратная матрица).
2. По вычисленному вектору ${\bf\lambda}$ оценивается давление согласно формуле $[{\bf P}^*({\bf
\lambda}) = {\bf P}_{\mathrm{mean}} + \sum_{i=1}^d\lambda_i{\bf e}_i^P.
]$

Задача состоит в том, чтобы реализовать предложенный алгоритм;
подсчитать график зависимости средней ошибки восстановления
векторов давлений из тестовой выборки от размерности сжатия $d$;
нарисовать несколько восстановленных графиков давления (для
нескольких разных профилей) с наложением истинных значений
давления. Ошибка между набором векторов $({\bf P}_i)_{i=1}^M$ и
восстановленными векторами $({\bf P}^*_i)_{i=1}^M$ оценивается
согласно формуле $\sqrt{\frac{1}{M}\sum_{i=1}^M\|{\bf P}_i-{\bf P}^*_i\|^2}$, где
$\|\cdot\|$ -- евклидово расстояние

In [26]:
import pandas as pd

In [27]:
data = pd.read_csv('A2P.txt', sep=" ", header=None)
data = data.drop(114, axis=1)

In [28]:
data

0         1         2         3         4         5         6    \
0    0.000000  0.000334  0.000841  0.001942  0.004899  0.008544  0.012635   
1    0.000000  0.000334  0.000841  0.001942  0.004899  0.008544  0.012635   
2    0.000000  0.002407  0.005409  0.010245  0.018965  0.026769  0.033867   
3    0.000000  0.002407  0.005409  0.010245  0.018965  0.026769  0.033867   
4    0.001114  0.002846  0.005096  0.008957  0.016417  0.023352  0.029759   
5    0.001114  0.002841  0.004493  0.006953  0.011180  0.014750  0.017869   
6    0.000744  0.002249  0.004082  0.007233  0.013736  0.020442  0.027285   
7    0.000354  0.002697  0.005643  0.010460  0.019280  0.027017  0.033733   
8    0.000676  0.003163  0.006414  0.011798  0.021707  0.030256  0.037431   
9    0.000676 -0.000638 -0.001846 -0.003154 -0.003398 -0.000861  0.004091   
10   0.000000  0.001557  0.003670  0.007329  0.014648  0.021853  0.028935   
11   0.000000  0.000817  0.001949  0.003882  0.007608  0.011092  0.014328   
12   0.000000  0.000678  0.001625  0.003587  0.008454  0.014245  0.020622   
13   0.000000  0.001250  0.002914  0.005786  0.011555  0.017314  0.023078   
14   0.000000  0.000753  0.001910  0.004091  0.008855  0.013887  0.018877   
15   0.000000  0.001033  0.002469  0.005028  0.010391  0.015967  0.021733   
16   0.000000  0.000944  0.002307  0.004704  0.009547  0.014324  0.018929   
17   0.000000  0.000592  0.001428  0.003131  0.007363  0.012489  0.018370   
18   0.000000  0.000597  0.001441  0.003154  0.007411  0.012566  0.018472   
19   0.000000  0.000838  0.002110  0.004493  0.009786  0.015610  0.021802   
20   0.000000  0.000838  0.002110  0.004493  0.009786  0.015610  0.021802   
21   0.000163  0.001645  0.003418  0.006417  0.012444  0.018457  0.024293   
22   0.000163  0.002201  0.004541  0.008290  0.015131  0.021190  0.026550   
23   0.000214  0.002008  0.004130  0.007704  0.014855  0.021997  0.029057   
24   0.000214  0.001451  0.002758  0.004932  0.009277  0.013636  0.017998   
25   0.000177  0.001611  0.003266  0.006066  0.011772  0.017627  0.023583   
26   0.000177  0.001953  0.004044  0.007440  0.013764  0.019485  0.024632   
27   0.000186  0.001559  0.002991  0.005436  0.010741  0.016642  0.023041   
28   0.000186  0.001799  0.003676  0.006757  0.012648  0.018165  0.023230   
29   0.000191  0.001562  0.002983  0.005410  0.010704  0.016624  0.023099   
..        ...       ...       ...       ...       ...       ...       ...   
367  0.000000 -0.000175 -0.000044  0.000492  0.002324  0.004949  0.008272   
368  0.000000  0.001649  0.003640  0.007167  0.014486  0.021919  0.029341   
369  0.000000  0.001643  0.003731  0.007338  0.014655  0.022004  0.029314   
370  0.000000 -0.000269 -0.000272 -0.000007  0.001233  0.003322  0.006219   
371  0.000000  0.001723  0.003972  0.007856  0.015695  0.023530  0.031288   
372  0.000000  0.001622  0.003750  0.007439  0.014940  0.022497  0.030033   
373  0.000000  0.001557  0.003593  0.007129  0.014350  0.021670  0.029008   
374  0.000000 -0.000217 -0.000203  0.000054  0.001214  0.003216  0.006055   
375  0.000000  0.001467  0.003408  0.006800  0.013778  0.020911  0.028108   
376  0.000000 -0.000205 -0.000145  0.000224  0.001634  0.003891  0.006965   
377  0.000005  0.002038  0.004556  0.008818  0.017256  0.025543  0.033643   
378  0.000005 -0.000740 -0.001365 -0.002024 -0.002038 -0.000570  0.001982   
379  0.000000  0.001651  0.003743  0.007405  0.015002  0.022694  0.030333   
380  0.000637  0.002706  0.005188  0.009301  0.017229  0.024770  0.031963   
381  0.000000  0.001932  0.004271  0.008235  0.016193  0.024169  0.032114   
382  0.000000  0.001792  0.003968  0.007654  0.015032  0.022395  0.029706   
383  0.000000  0.000807  0.001635  0.003009  0.005745  0.008465  0.011179   
384  0.000423  0.002702  0.005664  0.010584  0.019740  0.027864  0.034908   
385  0.000423  0.001802  0.003449  0.006161  0.011331  0.016182  0.020746   
386  0.000000  0.001650  0.003948  0.008196  0.017291  0.026297  0.034813   
387  0